export interface ManageAuthorReqModel {
  firstName: string,
  lastName: string,
  image: string,
  bornDate: string,
  dieDate: string,
  authorId: number,
  name: string,
  genre: string,
  bookName: string,
  genreId: number,
  bookId: number,
  imageLink: string,
  link: string,
}
